RANKING_REQUEST_QUEUE = "ia.ranking.request"
RANKING_RESPONSE_QUEUE = "ia.ranking.response"
RESUMO_REQUEST_QUEUE = "ia.resumo.request"
RESUMO_RESPONSE_QUEUE = "ia.resumo.response"
COMPARACAO_REQUEST_QUEUE = "ia.comparacao.request"
COMPARACAO_RESPONSE_QUEUE = "ia.comparacao.response"

TODAS_AS_FILAS = [
    RANKING_REQUEST_QUEUE,
    RANKING_RESPONSE_QUEUE,
    RESUMO_REQUEST_QUEUE,
    RESUMO_RESPONSE_QUEUE,
    COMPARACAO_REQUEST_QUEUE,
    COMPARACAO_RESPONSE_QUEUE,
]